language: go

go:
  - 1.12.x

env:
  - GO111MODULE=on

git:
  depth: 1

install: true

script:
  - go test -race -coverprofile=coverage.txt -covermode=atomic -v

after_success:
  - bash <(curl -s https://codecov.io/bash)