language: go
go:
- 1.12.x
services:
- docker
env:
- GO111MODULE=on
- secure: WOJxzBUyPWliCNrnLGWUL5cTTx4M9QMT9MMh1hG/Z052kN/5OX40NvDwG6D8ltEAwUNhohomKmXWcL1rELnFkLmwZ/W3kvwWxxewIR1wzqW+y2lir3delvCEdUHm98U2fasnhTUhir8sqnwMFO7IourktVShnUsEW9xea7f344MTe7+OWoUgJfmRSaG5ezFDCerK5OgzUVd61Zi9V50I8gWNjA+fuAA/ogLIdISXlAj5RHqOFRxRQROtD4MUcC8Dx5It5MFpZEfa0aRZvFOgKQVHaCZrPrmqT20fF3mnZfoq4zfaZ/vDy5cUl7U+FIWs6sZrTHxow3OWzohkSzEupgaXARM81tbyvikcAn/rjrm6bjhvKbDfzYPZcUtPMiZIVagEnmK2IumaV4vtKQOkU990R1CokMqx8JQVesN7B8ztRadX0DPUFZrnSs6rvrIuRr3CvwyGyLihmvzdeeADSYsnKyvzJCVkPJqK0yYncHazSpKIthRljdvrHYltmnsMCFdh0YpB4RoGb4B7yQMhifksJBDZeYkafBVrMQUhEPdur6ccMnB02oK2NKX9Qq+KH45jb0BdEsRGgK6oYTMixsnKAn2r+9l0V2w3xS0+KTGPGq3PBIvHOtBPAFkSdEjUP2u5s5fSJuE8U4eMgU6Zk0WF2IAOHNq0Ga3U5yekkd8=

git:
  depth: 1
install: true
script:
- go test -race -coverprofile=coverage.txt -covermode=atomic -v
after_success:
- bash <(curl -s https://codecov.io/bash)
- docker build -t qastub/deepmock:$TRAVIS_COMMIT .
- echo "$DOCKERHUB_PASSWORD" | docker login -u "$DOCKERHUB_USERNAME" --password-stdin
- docker push qastub/deepmock:$TRAVIS_COMMIT
