name: master

on: [push, pull_request, release]

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    env:
      DOCKER_IMAGE: wosai/deepmock
    steps:
      - name: Set up Go 1.x
        uses: actions/setup-go@v2
        with:
          go-version: ^1.14
        id: go
      - name: Check out code into the Go module directory
        uses: actions/checkout@v2
      - name: Test
        run: go test -race -coverprofile=coverage.txt -covermode=atomic -v ./...
      - name: Test Coverage Report
        run: bash <(curl -s https://codecov.io/bash)
      - name: Log into DockerHub
        if: ${{ github.event_name == 'release' }}
        uses: azure/docker-login@v1
        with:
          username: ${{ secrets.DOCKERHUB_ORG_USERNAME }}
          password: ${{ secrets.DOCKERHUB_ORG_ACCESS_TOKEN }}
      - name: Tag Docker Image
        if: ${{ github.event_name == 'release' }}
        run: |
          docker build -t $DOCKER_IMAGE:${{github.ref}} .
          docker push $DOCKER_IMAGE:${{github.ref}}